### ISSUE TITLE
There is a miner inside the container

### ISSUE THREAD

**Issue by riseprolol** [devilbox/docker-php-fpm-5.3#22]
kdevtmpfsi and kinsing
do not download it

**Comment by cytopia** [comment]
@riseprolol Can you back up this claim, by pointing me to the location inside the Dockerfile (or any other file) where this can be found?

**Comment by cytopia** [comment]
@riseprolol closing as spam. Feel free to point out where this miner is hidden.

**Comment by erlangparasu** [comment]
https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/initial-access-techniques-in-kubernetes-environments-used-by/ba-p/3697975
