### ISSUE TITLE
Can't install mysql

### ISSUE THREAD

**Issue by xiaomlove** [devilbox/docker-php-fpm-5.3#25]
This image does not contain any extensions to mysql, mysql, mysqli, pdo_mysql, and via `RUN docker-php-ext-install mysqli` it also reports the following error.
```
The command '/bin/sh -c docker-php-ext-install mysqli' returned a non-zero code: 1
```

**Comment by cytopia** [comment]
@xiaomlove It is only a base image and these are the available extensions: https://github.com/devilbox/docker-php-fpm-5.3#available-modules.

What you are looking for is this image:

https://github.com/devilbox/docker-php-fpm#php-modules

**Comment by xiaomlove** [comment]
It's OK now, great job!
